# Generated by Django 4.0.1 on 2022-01-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thomasshop', '0003_basket_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketItems',
            new_name='BasketItem',
        ),
    ]
